### ISSUE TITLE
Please bump pyhafas to 0.3.1

### ISSUE THREAD

**Issue by 00pi** [akloeckner/hacs-hafas#3]
Hi,
I was running the integration without issues for some time. Supposedly due to a change on the server side it stopped working. Hopefully the fix provided in pyhafas 0.3.1 will do.
Thanks, Robert

**Comment by akloeckner** [comment]
Bump. ;-) Thanks for poking us.

**Comment by 00pi** [comment]
Thank you so much, the integration is providing data again 😀
